site_groups = [
    "global.social",
    "ru.social",
    "global.video",
    "ru.video",
    "global.news",
    "ru.news",
    "global.shopping",
    "ru.shopping",
    "global.productivity_trap",
    "ru.productivity_trap",
]
sites = []
apps = []

[limits]
max_duration = "24h"
min_duration = "2h"
cooldown = "1h"
panic_delay = "5m"
