site_groups = [
    "global.social",
    "ru.social",
    "global.video",
    "ru.video",
    "global.news",
    "ru.news",
    "global.chat",
    "ru.chat",
    "global.productivity_trap",
    "ru.productivity_trap",
]
sites = []
apps = []

[limits]
max_duration = "4h"

[schedule]
enabled = true
days = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]
start = "06:00"
end = "09:00"
tz = "local"
