site_groups = [
    "global.social",
    "ru.social",
    "global.video",
    "ru.video",
    "global.news",
    "ru.news",
    "global.games",
    "ru.games",
]
sites = []
apps = []

[limits]
max_duration = "14h"
min_duration = "1h"
cooldown = "30m"
